name: build
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build Executable
      run: pyinstaller --onefile --clean TiktokStreamKeyGenerator.py
    - name: Clean up obsolete files
      run: rm -rf build TiktokStreamKeyGenerator.spec
    - name: Get some values needed for the release
      id: release_values
      run: |
        echo "release_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Upload DevBuild as release
      if: github.repository == 'Loukious/TikTokStreamKeyGenerator'
      run: |
        gh release upload devbuild --clobber dist/*
        gh release edit devbuild --title "DevBuild $RELEASE_TAG"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: ${{ env.release_tag }}
